# Default profile
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:;INIT=create schema IF NOT EXISTS DEMO;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  test:
    database:
      replace: none
  jpa:
    properties:
      hibernatedialect: org.hibernate.dialect.H2Dialect